/**
  * @file    cm_backtrace_port.c
  * @brief   Blocking UART sink for the crash tracer. Generated by AutoDebug.
  *
  * Deliberately register-level and blocking: a HardFault runs at priority -1, where
  * SysTick cannot fire, so anything whose timeout depends on HAL_GetTick() (printf via
  * HAL_UART_Transmit, most retargets) spins forever and emits nothing at all.
  *
  * Regenerate for another port with:
  *     python run_autodebug.py --install-tracer --uart USART2 --family g4
  */
#include "cm_backtrace_lite.h"
#include "stm32f10x.h"

#define CM_BT_UART   USART1
#define CM_BT_TXE    (1U << 7)      /* TXE is bit 7 of SR on every STM32 USART */

void cm_backtrace_putchar(char c)
{
    /* The UART must already be initialised by the application before a crash occurs. */
    while ((CM_BT_UART->SR & CM_BT_TXE) == 0U) {
        /* spin: no SysTick, no HAL, no timeout that could never expire */
    }
    CM_BT_UART->DR = (uint8_t)c;
}
